<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>E_Commerce.Presentation</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\E Commerce.Services Abstraction\E Commerce.Services Abstraction.csproj" />
  </ItemGroup>

	<ItemGroup>
		<FramworkReference Include="Microsoft.AspNetCore.App"/>	
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
	</ItemGroup>	
</Project>
